name: MaxPlayers
version: 1.0
author: Caleb Bassham
main: me.calebbassham.maxplayers.MaxPlayers
api-version: 1.13

commands:
    maxplayers:
        usage: /<command> <max players (INT)> [kick overflow (TRUE/FALSE)=FALSE]
        permission: maxplayers.set